VIRTUAL_ENV_DISABLE_PROMPT=1

ZSH_THEME_GIT_PROMPT_PREFIX="|g:"
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY="⎁"
ZSH_THEME_GIT_PROMPT_CLEAN=""

PROMPT='
%d %F{240}$(git_prompt_info)|$(echo `basename "$VIRTUAL_ENV"`)|
%(1j.%j.)%f$ '
